version: '2.4'

services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariaDB
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    env_file:
      - env.env
    volumes:
      - db_data:/home/yann/data
    ports: 
      - 3306:3306
    networks:
      - network
  nginx: 
    image: nginx
    depends_on: 
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - app:/var/www/html/wordpress
    networks:
      - network
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress+php_fpm
      dockerfile: Dockerfile
    depends_on: 
      - mariadb
    restart: always
    container_name: wordpress
    env_file:
      - env.env
    volumes:
      - app:/var/www/html/wordpress
    ports: 
      - 9000:9000
    networks:
      - network

volumes:
  db_data: {}
  app: {}

networks:
  network:
    driver: bridge 
